### ISSUE TITLE
[Bug]: Getting Bug when starting tasks

### ISSUE THREAD

**Issue by KaranBhullar** [Weyaaron/nvim-training#52]
### Describe the bug

I am getting a weird bug when I try to do tasks. Some tasks work just fine but others cause errors. 

![Image](https://github.com/user-attachments/assets/be0a0f5a-a63c-42ab-acf1-339df397b501)

I attempted to solve that task by using `5j` and I got the error:

![Image](https://github.com/user-attachments/assets/b381e3f0-b65f-4226-8da3-3a6c7dcc872c)

There are some other tasks where I would enter Insert mode and then press `<Esc>` to leave it but I would end up with similar errors.

For some additional context, I am using Packer to install this, not Lazy. I also tried configuring it using the example configuration and with nothing but events disabled. Here is my current setup:

![Image](https://github.com/user-attachments/assets/106cfc16-ba2c-4ba9-836c-d57e7b3772f0)

![Image](https://github.com/user-attachments/assets/f8d87588-3c84-40df-a435-c638f38f7210)

### How to reproduce the behavior

```markdown
`:Training Start RandomScheduler`
```

### Expected behavior.

N/A 

### Logs and Stack traces

```stacktrace

```

### Environment

```markdown
MacOS M2 chip using Iterm2 as the terminal.
```

**Comment by Weyaaron** [comment]
Thanks for letting me know, I appreciate the effort. 

This is a known bug that has been fixed on the main branch and should not happen again. I will double check and report back.

**Comment by Weyaaron** [comment]
I have double checked, please ensure you update to include up to commit https://github.com/Weyaaron/nvim-training/commit/f07bb3642ba6f4c4b0b5522f32dffe574d8f9c10

This should solve the issue, let me know if it does.

**Comment by KaranBhullar** [comment]
I still have a persistent error. On this task:

![Image](https://github.com/user-attachments/assets/0f56cba9-b0b0-43e1-97c0-b0771c5b48af)

I will get this error:

![Image](https://github.com/user-attachments/assets/187e2150-c32b-49ca-8b06-f7f7de158837)

Here is my current configuration:

![Image](https://github.com/user-attachments/assets/a3d680d6-3aea-406c-810b-0e2773df4d1e)

Note that I set `enable_events` to `false` because when I keep it enabled, along with the file path, it gives me another issue:
 "Unable to create the path '/{...}/.local/share/nvim/nvim-training/'. The plugin will not run. If this path does not suit you, use 'configure' to set it or disable events using 'configure'"

**Comment by Weyaaron** [comment]
I did some digging and decided to temporarily disable logging and event storage. This has been a mess, sorry for the inconvenience. 

Please update up to #53 and the plugin should work. If it does, please close the issue.
